# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cbrowser', '0002_links_l_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dp',
            field=models.CharField(default='https://thebenclark.files.wordpress.com/2014/03/facebook-default-no-profile-pic.jpg', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.IntegerField(default=0),
        ),
    ]
