# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cbrowser', '0004_auto_20170227_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dp',
            field=models.CharField(default='https://thebenclark.files.wordpress.com/2014/03/facebook-default-no-profile-pic.jpg', max_length=1000),
        ),
    ]
